// <auto-generated />
using Amadeus.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Amadeus.Db.Migrations
{
    [DbContext(typeof(AmadeusContext))]
    [Migration("20210711072650_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresEnum(null, "cs_type", new[] { "string", "boolean", "int", "char" })
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Amadeus.Db.Models.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ConfigOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("config_option_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_configs");

                    b.HasIndex("ConfigOptionId")
                        .HasDatabaseName("ix_configs_config_option_id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_configs_guild_id");

                    b.ToTable("configs");
                });

            modelBuilder.Entity("Amadeus.Db.Models.ConfigOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ConfigOptionCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("config_option_category_id");

                    b.Property<int>("CsType")
                        .HasColumnType("integer")
                        .HasColumnName("cs_type");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_config_options");

                    b.HasIndex("ConfigOptionCategoryId")
                        .HasDatabaseName("ix_config_options_config_option_category_id");

                    b.ToTable("config_options");
                });

            modelBuilder.Entity("Amadeus.Db.Models.ConfigOptionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_config_option_categories");

                    b.ToTable("config_option_categories");
                });

            modelBuilder.Entity("Amadeus.Db.Models.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_guilds");

                    b.ToTable("guilds");
                });

            modelBuilder.Entity("Amadeus.Db.Models.Config", b =>
                {
                    b.HasOne("Amadeus.Db.Models.ConfigOption", "ConfigOption")
                        .WithMany("Configs")
                        .HasForeignKey("ConfigOptionId")
                        .HasConstraintName("fk_configs_config_options_config_option_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amadeus.Db.Models.Guild", "Guild")
                        .WithMany("Configs")
                        .HasForeignKey("GuildId")
                        .HasConstraintName("fk_configs_guilds_guild_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigOption");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Amadeus.Db.Models.ConfigOption", b =>
                {
                    b.HasOne("Amadeus.Db.Models.ConfigOptionCategory", "ConfigOptionCategory")
                        .WithMany("ConfigOptions")
                        .HasForeignKey("ConfigOptionCategoryId")
                        .HasConstraintName("fk_config_options_config_option_categories_config_option_categ")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigOptionCategory");
                });

            modelBuilder.Entity("Amadeus.Db.Models.ConfigOption", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("Amadeus.Db.Models.ConfigOptionCategory", b =>
                {
                    b.Navigation("ConfigOptions");
                });

            modelBuilder.Entity("Amadeus.Db.Models.Guild", b =>
                {
                    b.Navigation("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
