// <auto-generated />
using Amadeus.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Amadeus.Db.Migrations
{
    [DbContext(typeof(AmadeusContext))]
    [Migration("20210715160237_ProfileEntry")]
    partial class ProfileEntry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresEnum(null, "cs_type", new[] { "string", "boolean", "int", "char" })
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Amadeus.Db.Models.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ConfigOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("config_option_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_configs");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_configs_guild_id");

                    b.ToTable("configs");
                });

            modelBuilder.Entity("Amadeus.Db.Models.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_guilds");

                    b.ToTable("guilds");
                });

            modelBuilder.Entity("Amadeus.Db.Models.ProfileEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ProfileFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_field_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_profile_entries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_profile_entries_user_id");

                    b.ToTable("profile_entries");
                });

            modelBuilder.Entity("Amadeus.Db.Models.User", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Amadeus.Db.Models.Config", b =>
                {
                    b.HasOne("Amadeus.Db.Models.Guild", "Guild")
                        .WithMany("Configs")
                        .HasForeignKey("GuildId")
                        .HasConstraintName("fk_configs_guilds_guild_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Amadeus.Db.Models.ProfileEntry", b =>
                {
                    b.HasOne("Amadeus.Db.Models.User", "User")
                        .WithMany("ProfileEntries")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_profile_entries_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amadeus.Db.Models.Guild", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("Amadeus.Db.Models.User", b =>
                {
                    b.Navigation("ProfileEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
